### ISSUE TITLE
Input identical to output

### ISSUE THREAD

**Issue by ekernf01** [WGLab/GenGen#1]
Hi WGlab,

I am using `convert_bim_allele.pl` to get forward-strand nucleotides from Illumina top-strand nucleotides. When I run this command, though, the input is identical to the output.

     convert_bim_allele.pl \
	data_for_gengen_demo.bim our_array.snptable \
	-intype top -outtype forward \
	-outfile data_for_gtool.bim \
	--strandfile our_strand_info.strand

I am attaching the files I've used. I appreciate your help!

[demo_data.zip](https://github.com/WGLab/GenGen/files/800824/demo_data.zip)

Eric

**Comment by kaichop** [comment]
you may want to check your snptable file to make sure that it is correct
and that it contains all markers in your bim file.

**Comment by ekernf01** [comment]
It turns out my data were in forward-strand format all along. Sorry for the bother!
