### ISSUE TITLE
Core dump

### ISSUE THREAD

**Issue by lpalomerol** [WGLab/GenGen#2]
Hello people.

I am trying to work with your awesome solution and I am experiencing a weird core dump problem. I've been debugging your code until reaching the problematic line at method XS(_wrap_chi2test_2by2table), concretely after launching chi2test_2b2table method.

    chi2test_2by2table(arg1,arg2,arg3);

    ST(argvi) = sv_newmortal();
    {
      unpack1D((SV*)_saved[0], (void *)arg1, 'd', 0); //Core dump at this line.
    }
    {
      SV *tempsv;
      tempsv = SvRV(_saved[1]);
      sv_setnv(tempsv, *arg2);
    }
    {
      SV *tempsv;
      tempsv = SvRV(_saved[2]);
      sv_setnv(tempsv, *arg3);
    }

Seems that the problem could be in the integration between c and perl. Maybe the compilation? I've performed the make with the standart options too.

Thank you for this awesome package!

Luis.

**Comment by kaichop** [comment]
were you able to re-compile the source code, before you run the program?
There are a couple of reasons, but most likely it is because the old perl-C
conversion code no longer works with latest version of Perl API, or no
longer works with the latest version of GCC (assuming that you are using
gcc4 or gcc5). I am in the process of re-organizing older files and I will
check if using a newer version of swig to generate a new C code can solve
this problem.

**Comment by lpalomerol** [comment]
Hello Kai,

thank you for your early response! 

My gcc version is 4.8.5 and my perl is 5.16.3.

And the problem occurs when launghing a calculate_association.pl file with this isntruction:
 
    /home/idibell/opt/gengen/GenGen-1.0.1/calculate_association.pl -cc -plink  \

    ../results/20180221.perform.gwas/1.trasposed/tmpTrasposed.tfam  \

    ../results/20180221.perform.gwas/1.trasposed/tmpTrasposed.tped -out   \

    ../results/20180221.perform.gwas/2.association/out
 

What do you suggest? Try another gcc/perl version?, wait your fixup?

Thank you again!

**Comment by kaichop** [comment]
The easiest way is probably just install a lower version of perl, then
compile again (after setting appropriate path that has the new perl ahead
of old perl)

http://penncnv.openbioinformatics.org/en/latest/user-guide/install/#the-last-resort

**Comment by lpalomerol** [comment]
Thanks! I'll try it and I'll confirm you if it has worked

2018-02-23 14:52 GMT+01:00 Kai Wang <notifications@github.com>:

**Comment by lpalomerol** [comment]
Hello again,

still not working, I've tried with perl 5.14 version and gives me same error. Do you suggest any concrete version?

This is the core trace of performed process with 5.14 version (go to kext folder, make clean, make, go back and perform association test). Any help would be appreciated

`

    lpalomero ~/Documentos/pipelines/8.pujana/20180219.comorbidity/bin $ cd ~/opt/gengen/GenGen-1.0.1/kext/; make clean; make; cd -;
rm -f *.o *.so
gcc `perl -MExtUtils::Embed -e ccopts` -fPIC   -c -o kc_wrap.o kc_wrap.c
gcc `perl -MExtUtils::Embed -e ccopts` -fPIC   -c -o kc.o kc.c
gcc -shared -o kc.so kc_wrap.o kc.o `perl -MExtUtils::Embed -e ldopts`
mkdir -p `perl -MConfig -e 'print $Config{version}'`
mkdir -p `perl -MConfig -e 'print $Config{version}'`/`perl -MConfig -e 'print $Config{archname}'`/
mkdir -p `perl -MConfig -e 'print $Config{version}'`/`perl -MConfig -e 'print $Config{archname}'`/auto/
mv kc.so `perl -MConfig -e 'print $Config{version}'`/`perl -MConfig -e 'print $Config{archname}'`/
/home/idibell/Documentos/pipelines/8.pujana/20180219.comorbidity/bin
    
    lpalomero ~/Documentos/pipelines/8.pujana/20180219.comorbidity/bin $ perl -v

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-thread-multi

Copyright 1987-2011, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at http://www.perl.org/, the Perl Home Page.

    lpalomero ~/Documentos/pipelines/8.pujana/20180219.comorbidity/bin $             
    /home/idibell/opt/gengen/GenGen-1.0.1/calculate_association.pl -cc -plink 
    ../results/20180221.perform.gwas/1.trasposed/tmpTrasposed.tfam 
    ../results/20180221.perform.gwas/1.trasposed/tmpTrasposed.tped -out 
    ../results/20180221.perform.gwas/2.association/out

NOTICE: program notification/warning messages that appear in STDERR will be also recorded in log file ../results/20180221.perform.gwas/2.association/out.log
NOTICE: detailed genotyping summary information for all markers (even if not passing quality control threshold) will be written to ../results/20180221.perform.gwas/2.association/out.minfo
NOTICE: detailed genotyping summary information for all samples will be written to ../results/20180221.perform.gwas/2.association/out.sinfo
NOTICE: detailed genotyping summary information for all families with Mendelian errors will be written to ../results/20180221.perform.gwas/2.association/out.finfo
NOTICE: the following marker exclusion criteria is in effect: --geno 0.1 --maf 0.01 --mme 0.1 --hwe 0.001
NOTICE: the following individual exclusion criteria will *NOT* be used in association test
        However, individuals failing these criteria will be recorded for re-running program (with --remove argument): --mind 0.1 --fme 1 --ime 0.02
NOTICE: Finished reading pedigree information for 2287 individuals from header file ../results/20180221.perform.gwas/1.trasposed/tmpTrasposed.tfam
NOTICE: Current pedigree contains 2287 families with 2287 individuals
        Sex: 0 are male, 2287 are female, 0 are of unknown sex
        Founder: 2287 are founders, 0 are non-founders
        Phenotype (binary trait): 1142 are unaffected, 1145 are affected, and 0 are unknown

Violación de segmento (`core' generado)
`

**Comment by lpalomerol** [comment]
Hello!

Finally I could run it successfully using PERL version 5.8.9 instead of 5.14

Thank you!

**Comment by kaichop** [comment]
Thank you for the update. This is good to know that it is caused by perl
version issues.
