### ISSUE TITLE
calculate_gsea.pl P_PERM column not found

### ISSUE THREAD

**Issue by shraddhapai** [WGLab/GenGen#7]
Hi Kai, 
Thank you for writing gengen; I use it in my projects for pathway analysis.

When the --pvalue_flag is set, calculate_gsea.pl seems to be searching for a column named "_P_PERM" rather than "P_PERM". I kept getting an error with a column named as the latter, and modifying line 306 to "P_PERM" fixed the issue.
Either the documentation needs to be fixed, or that line does, to clarify what header to expect.

Thanks and regards,
Shraddha

**Comment by kaichop** [comment]
The column name depends on how the permuted p-values are generated. I have updated the script to look for P_PERM instead.

**Comment by shraddhapai** [comment]
Thanks, Kai.
Best,Shraddha
